sudo: false
language: node_js
node_js:
  - "6"
before_install:
  - npm install -g Financial-Times/origami-build-tools@^&
  - obt install
script:
  - obt verify
  - obt test
cache:
  directories:
  - node_modules
